// Generated by CoffeeScript 1.6.3
(function() {
  var createTexturedPoly, renderer, stage, textureProps0, textureProps1, textureProps2, textureProps3;

  createTexturedPoly = function(poly, props) {
    var canvas, context, img, pattern, point, scaledCanvas, scaledContext, scaledHeight, scaledWidth, _i, _len;
    img = PIXI.TextureCache[props.src].baseTexture.source;
    canvas = document.createElement('canvas');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    context = canvas.getContext('2d');
    if (props.scaleX !== 1 || props.scaleY !== 1) {
      scaledCanvas = document.createElement('canvas');
      scaledContext = scaledCanvas.getContext('2d');
      scaledWidth = props.scaleX * img.width;
      scaledHeight = props.scaleY * img.height;
      scaledCanvas.width = scaledWidth;
      scaledCanvas.height = scaledHeight;
      scaledContext.drawImage(img, 0, 0, img.width, img.height, 0, 0, scaledWidth, scaledHeight);
      img = scaledCanvas;
    }
    pattern = context.createPattern(img, 'repeat');
    context.beginPath();
    context.moveTo(poly[0].x, poly[0].y);
    for (_i = 0, _len = poly.length; _i < _len; _i++) {
      point = poly[_i];
      context.lineTo(point.x, point.y);
    }
    context.fillStyle = pattern;
    if (props.rotation !== 0) {
      context.rotate(props.rotation * 0.0174532925);
    }
    context.fill();
    return new PIXI.Sprite(PIXI.Texture.fromCanvas(canvas));
  };

  renderer = null;

  stage = null;

  textureProps0 = {
    scaleX: .1,
    scaleY: .1,
    rotation: 90,
    src: 'grass.jpg'
  };

  textureProps1 = {
    scaleX: 1,
    scaleY: 1,
    rotation: 90,
    src: 'wood-pattern.png'
  };

  textureProps2 = {
    scaleX: 0.7,
    scaleY: 0.4,
    rotation: 15,
    src: 'rock1.jpg'
  };

  textureProps3 = {
    scaleX: 3,
    scaleY: 3,
    rotation: 90,
    src: 'rock2.jpg'
  };

  window.onload = function() {
    var assetsToLoad, loader;
    renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight);
    stage = new PIXI.Stage(0xff0000);
    document.body.appendChild(renderer.view);
    assetsToLoad = ['wood-pattern.png', 'rock1.jpg', 'rock2.jpg', 'grass.jpg'];
    loader = new PIXI.AssetLoader(assetsToLoad);
    loader.onComplete = function() {
      var sprite1, sprite2, sprite3;
      sprite1 = createTexturedPoly([new PIXI.Point(0, 0), new PIXI.Point(window.innerWidth, 0), new PIXI.Point(window.innerWidth, window.innerHeight), new PIXI.Point(0, window.innerHeight / 2)], textureProps0);
      stage.addChild(sprite1);
      sprite2 = createTexturedPoly([new PIXI.Point(60, 60), new PIXI.Point(10, 0), new PIXI.Point(850, 50), new PIXI.Point(100, 800), new PIXI.Point(50, 80), new PIXI.Point(0, 100)], textureProps1);
      stage.addChild(sprite2);
      sprite3 = createTexturedPoly([new PIXI.Point(60, 60), new PIXI.Point(10, 0), new PIXI.Point(850, 50), new PIXI.Point(100, 800), new PIXI.Point(50, 80), new PIXI.Point(0, 100)], textureProps2);
      sprite3.position = {
        x: 100,
        y: 100
      };
      stage.addChild(sprite3);
      return renderer.render(stage);
    };
    loader.load();
    return console.log(loader);
  };

}).call(this);
